# Generated by Django 4.2.13 on 2024-06-28 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.JSONField()),
                ('author', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('url', models.URLField()),
                ('urlToImage', models.URLField(max_length=500)),
                ('publishedAt', models.DateTimeField()),
                ('content', models.TextField()),
            ],
        ),
    ]
